name: Create Azure VM

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up PowerShell
        uses: actions/setup-powershell@v2

      - name: Login to Azure using Service Principal
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "d7c53bde-1276-4218-b32f-0265181d4af6" 
            }

      - name: Run PowerShell script to create VM
        shell: pwsh
        env:
          VM_USERNAME: ${{ secrets.VM_USERNAME }}
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
        run: |
          pwsh ./create-vm.ps1 -vmUsername $env:VM_USERNAME -vmPassword $env:VM_PASSWORD
